### PR TITLE
Add online version with clickable TOC and Index

### PR DESCRIPTION
**Pull request by gabindu**
... to make TOC, bib, and index hyperlinked (and more)

### CODE REVIEW

**Comment by gabindu** [comment]
I've updated this to match the latest version from the upstream repository, and this could now be immediately merged without any disadvantages. The main changes are:

- Create a new masterfile `Probability_Notes_online.tex` which creates a pdf-file with Table of Content, clickable links, and an Index.
- Create a Makefile which enables compilation with the simple command `make` (this uses `latexmk` behind the scenes).  This automatically copies the produced pdf-files into a new folder `BUILD/`.
- The automatically created final pdf-files (as well as temporary files `*.gnuplot` and `*.table`) are removed from the repository (as is common practice, since they can be reproduced from the sources).
- Content: a few forgotten `\text{Var}` were replaced by `\Var`, and the definition of `\Var` was changed to be a MathOperator (behaves better in LaTeX).  No other content was changed.

**Comment by qubd** [comment]
I just added the files generated by gnuplot to the gitignore. I will not remove the final pdf from this repository as part of the point of this repo is to be a place where people can find that (without going through the headache of installing all the dependencies required to compile it).

I _think_ the content changes are all merged already.

About the \Var operator: I recall using \text{Var} a number of times to manually correct instances where it was appearing italicized in places it should not (in equations I think). Sometime soon I'll mess around a bit to see if your changes fixed this, and take a look at the online version as well, then get back to you and close this request.

I'm not going to add the makefile. I want to keep the list of dependencies from exploding too much, and I'd like to stay as close as possible to "vanilla latex" and gnuplot so as not to intimidate those who run across this repo.

**Comment by gabindu** [comment]
> I just added the files generated by gnuplot to the gitignore.

There are still more additions to the .gitignore which should be included.

> I will not remove the final pdf from this repository as part of the point of this repo is to be a place where people can find that (without going through the headache of installing all the dependencies required to compile it).

That's of course your prerogative, and you could easily add it back in after merging this PR.

> I _think_ the content changes are all merged already.

You can check by clicking on "Files changed" here on Github - there's still quite a few changes outstanding which I think should be merged.
 
> About the \Var operator: I recall using \text{Var} a number of times to manually correct instances where it was appearing italicized in places it should not (in equations I think). Sometime soon I'll mess around a bit to see if your changes fixed this, and take a look at the online version as well, then get back to you and close this request.

The `\DeclareMathOperator` which I used in the definition of `\Var` should correctly take care of the proper formatting in all cases - I think you had to do manual corrections before, because that was not the way it was defined. In any case, I just replaced every occurrence of `Var` or `\text{Var}` by `\Var` which (as far as I can tell) produces a perfect result in all cases.

> I'm not going to add the makefile. I want to keep the list of dependencies from exploding too much, and I'd like to stay as close as possible to "vanilla latex" and gnuplot so as not to intimidate those who run across this repo.

IMHO, a Makefile is as "vanilla" as it gets (the `make` command is preinstalled on all modern [at least Unix-like] operating systems) - and it is not using anything that's not already been used (it just calls `latexmk` on the required targets, which is part of every TeX distribution, and is how one should compile a LaTeX document these days anyways). In fact, the existence of the Makefile in no way hinders anyone who wants to compile the tex-file manually, but it adds the convenience of not having to worry about which tex-file is the "master" file, and whether there are any more dependencies, which is precisely why most projects have a Makefile in the first place. This is especially useful when there are more than one targets, as in this case for the online-version with hyperlinked TOC and the original version. (That being said, I actually believe there is no reason to still keep the non-hyperref version around, as the "online" version can be printed in the same way and only adds value and no downsides.)

When in doubt, it would be a good idea to add a `README.md` with (optionally context for the whole project and) compile instructions (which in this case could be as short as "run `make`"). ;-)

**Comment by gabindu** [comment]
The only merge conflict is in the `.gitignore`, since you independently added part of the same content as my version already had. Since my version contains all these, you could safely accept that as the new version.

**Comment by qubd** [comment]
Okay sounds good. Just checked the changes to the \Var operator are all working.

I'll merge this, then make a commit removing some files and editing the gitignore.

In the future I'd appreciate it if you could make separate pull requests for changes to the content of the notes and any other changes you might want to contribute (should be clear that this is helpful now that our branches are going to differ).

I'll add a README soon.

**Comment by gabindu** [comment]
> In the future I'd appreciate it if you could make separate pull requests for changes to the content of the notes and any other changes you might want to contribute (should be clear that this is helpful now that our branches are going to differ).

I actually did - I originally opened this merge request over two years ago, with just the structural changes to create the online version... ;-)    Since you didn't approve the merge request and in the meantime then also changed your sources, I adjusted this branch to follow along and avoid merge conflicts and make things easier for you.

But I hear ya, I'll definitely try to keep things separate in the future.

**Comment by gabindu** [comment]
...and you're welcome... ;-)

**Pull request merged**
